### PR TITLE
1357 fix dataviews analysis states

### LINKED ISSUE #1357: Dataviews should be in loading state while its related analysis is not ready
Related to https://github.com/CartoDB/cartodb/issues/8365, the dataviews should also be in `loading` when the related analysis doesn't have status `ready` or `failed`

### PR DESCRIPTION
**Pull request by viddo**
Fixes #1357 

_WIP_

### CODE REVIEW

**Comment by viddo** [comment]
@alonsogarciapablo this is what I have in mind at the moment, would like some early feedback before I continue more, in case I'm overlooking something or if you think I should solve this in another way?

File: src/dataviews/dataview-model-base.js [hunk 1]
```diff
@@ -76,6 +78,7 @@ module.exports = Model.extend({
 
   _initBinds: function () {
     this.listenTo(this.layer, 'change:visible', this._onLayerVisibilityChanged);
+    this.listenTo(this.layer, 'change:source', this._onLayerVisibilityChanged);
```
Comment (alonsogarciapablo) [inline src/dataviews/dataview-model-base.js]: Do we need this?

**Comment by alonsogarciapablo** [comment]
Current approach seems good to me 👍. Keep going!

File: src/dataviews/dataview-model-base.js (hunk 1 above)
Comment (viddo) [inline src/dataviews/dataview-model-base.js]: Yes, it's my understanding by looking at the code and take into consideration that the source will change from time to time (e.g. adding/remove nodes in the builder). 
So when the head node of the layer (i.e. source) changes we would need to make sure [the correct analysis](https://github.com/CartoDB/cartodb.js/blame/1357-fix-dataviews-analysis-states/src/dataviews/dataview-model-base.js#L103) is listened to.

Comment (alonsogarciapablo) [inline src/dataviews/dataview-model-base.js]: `this._onLayerVisibilityChanged` ?

Comment (alonsogarciapablo) [inline src/dataviews/dataview-model-base.js]: Aren't we taking care of that [here](https://github.com/CartoDB/cartodb.js/pull/1359/files/ab4d43799e3ba602de36efbe15339ecbf76f0f2f#diff-805364e485d740e26e33839755aab753R97)?

Comment (viddo) [inline src/dataviews/dataview-model-base.js]: Hmm not sure I follow you… do you mean that the visibility of the layer should influence what `getSourceId` returns? E.g. if layer is not visible return the own source instead?

Comment (viddo) [inline src/dataviews/dataview-model-base.js]: Argh, misread… yeah that's wrong, I'll fix that

**Comment by viddo** [comment]
Done, @alonsogarciapablo please have a look again. I've been making some quick tests (using `npm link` on DI + cdb in the builder and network conditions set), and it seems to be working now.

File: src/dataviews/dataview-model-base.js [hunk 2]
```diff
@@ -87,9 +89,45 @@ module.exports = Model.extend({
...
+    this._analysis = this._analysisCollection.get(this.getSourceId());
+    if (this._analysis) {
+      this._analysis.on('change:status', this._onAnalysisStatusChange, this);
+    }
+  },
+
+  _removeExistingAnalysisBindings: function () {
+    if (!this._analysis) return;
+
+    this.layer.off('change:status', this._onAnalysisStatusChange, this);
```
Comment (alonsogarciapablo) [inline src/dataviews/dataview-model-base.js]: Do layers have a `status` attribute?

File: src/dataviews/dataview-model-base.js [hunk 3]
```diff
@@ -225,6 +263,7 @@ module.exports = Model.extend({
     return this.getSourceId() === this.layer.get('source');
   },
 
+  // @return might return undefined if there's no source
```
Comment (alonsogarciapablo) [inline src/dataviews/dataview-model-base.js]: I don't think this is true, given that we're always setting a source in the dataviewFactory.

File: test/spec/dataviews/dataview-model-base.spec.js [hunk 4]
```diff
@@ -536,4 +568,51 @@ describe('dataviews/dataview-model-base', function () {
...
+        loading: this.loadingSpy = jasmine.createSpy('loading'),
+        error: this.errorSpy = jasmine.createSpy('failed')
+      });
+    });
+
+    sharedTestsForAnalysisEvents();
+
+    describe('when changed source', function () {
+      beforeEach(function () {
+        this.model.set('source', {id: 'a0'});
```
Comment (alonsogarciapablo) [inline test/spec/dataviews/dataview-model-base.spec.js]: Wasn't source already `{id: 'a0'}`? (https://github.com/CartoDB/cartodb.js/pull/1359/files#diff-f3d05477ce22032bf6eedd3d279090f1R18)

**Comment by alonsogarciapablo** [comment]
Left two minor comments! Other than those two... 👏 👏 👏

File: src/dataviews/dataview-model-base.js (hunk 2 above)
Comment (viddo) [inline src/dataviews/dataview-model-base.js]: no you're right…

File: src/dataviews/dataview-model-base.js (hunk 3 above)
Comment (viddo) [inline src/dataviews/dataview-model-base.js]: Right, this comment was written before I added the guard in the initialize too. I'll 🔥

File: test/spec/dataviews/dataview-model-base.spec.js (hunk 4 above)
Comment (viddo) [inline test/spec/dataviews/dataview-model-base.spec.js]: Considering the source is an _object_ and not a value we're technically creating a new object here, so the equality check would "fail" and it would set this as a "new' value and thus trigger an event.
