### PR TITLE
Fixes vector layer rendering

### LINKED ISSUE #1399: vector=true maps broken
I guess mostly related to [show/hide layer](https://github.com/CartoDB/cartodb.js/pull/1376) changes.

screen shot 2016-09-01 at 14 35 10

### PR DESCRIPTION
**Pull request by alonsogarciapablo**
fixes #1399

cc: @rochoa

### CODE REVIEW

File: src/geo/cartodb-layer-group-view-base.js [hunk 1]
```diff
@@ -18,7 +16,7 @@ CartoDBLayerGroupViewBase.prototype = {
 
     // Enable interaction for the layers that have interaction
     // (are visible AND have tooltips OR infowindows)
-    _.each(this.model.getLayers(), function (layer, layerIndex) {
+    this.model.each(function (layer, layerIndex) {
```
Comment (rochoa) [inline src/geo/cartodb-layer-group-view-base.js]: 👍

File: src/geo/cartodb-layer-group.js [hunk 2]
```diff
@@ -131,10 +139,18 @@ var CartoDBLayerGroup = Backbone.Model.extend({
 
   onLayerVisibilityChanged: function (callback) {
     this._layersCollection.on('change:visible', function (layerModel) {
-      if (this.getLayers().indexOf(layerModel) >= 0) {
+      if (this.contains(layerModel)) {
         callback(layerModel);
```
Comment (rochoa) [inline src/geo/cartodb-layer-group.js]: Off-topic: one thing I usually do is always `return callback(...);`, so if later I add other branches to the code it will not call callback more than once.

Comment (alonsogarciapablo) [inline src/geo/cartodb-layer-group.js]: Good to know! Thanks!
