### PR TITLE
Do not rely on object.offsetParent when the map is fixed to the top.

### LINKED ISSUE #639: Bug in IE and Firefox when map div is position fixed
This is the same bug as reported here: https://github.com/CartoDB/cartodb.js/issues/114

It now works in Chrome and Safari, but there is still an offset bug in Firefox and IE 8, 9, 10 and Edge. 

To reproduce the bug (using CartoDB.js 3.15.1):

1. Go to this page: http://thematicmapping.org/playground/cartodb/bugs/fixedpos.html
2. Scroll down the page (most of our maps are embedded in news articles).
3. Click the fullscreen button. We're using a fixed positioned div to show the map in fullscreen. 
4. Click on a region, the popup is shown far off the map and not where the user clicked. 
5. Popups in Leaflet works as expected in all browsers, so this is a CartoDB.js bug. 

screen shot 2015-08-05 at 14 07 08
 
Hope this bug will be fixed across all browsers and devices :-)

### PR DESCRIPTION
**Pull request by alonsogarciapablo**
Fixes #639.

In some circumstances, the map can be fixed to the top but the page might have some scroll that we need to take into account. In these cases it's better not to use the object.offsetParent approach.

@xavijam what do you think?

### CODE REVIEW

**Comment by alonsogarciapablo** [comment]
As a bonus, I discovered an fixed [this other bug](https://github.com/CartoDB/cartodb.js/commit/6d916ab1b3a2a506eb82e42aa7af09e1db0cc613).

**Comment by alonsogarciapablo** [comment]
@xavijam do you think we should fix this [here](https://github.com/CartoDB/cartodb.js/blob/develop/src/geo/gmaps/gmaps_cartodb_layergroup.js#L232-L254) too? Thanks!

**Comment by alonsogarciapablo** [comment]
Retest this please

**Comment by alonsogarciapablo** [comment]
retest this please

**Comment by jesusvazquez** [comment]
retest this please

**Comment by xavijam** [comment]
@alonsogarciapablo, yes, we should fix there too.
About the PR en general, I love the idea (and the fix) but probably we should take care of GMaps too, shouldn't we?

**Comment by xavijam** [comment]
Also, could we create a test trying this with a fixed or a relative map div?

**Comment by alonsogarciapablo** [comment]
@xavijam Thanks for your feedback! I've [fixed it for GMaps](https://github.com/CartoDB/cartodb.js/commit/b65d0a881115ef8767017d2be63851b5600ee002) and also uploaded a [basic example that reproduces the issue](https://github.com/CartoDB/cartodb.js/commit/08f85c2efc72393c466a8a5116894f5bbb121f59).

**Comment by xavijam** [comment]
yay, have you tested for old browsers (IE7-9)? Just to keep legacy compatibility :S.

File: src/geo/leaflet/leaflet_cartodb_layergroup.js [hunk 1]
```diff
@@ -277,22 +278,32 @@ L.CartoDBGroupLayerBase = L.TileLayer.extend({
...
+        (o.e.clientY? o.e.clientY: y) - rect.top - obj.clientTop - scrollY);
     }
-  }
+    return map.containerPointToLayerPoint(point);
+  },
 
+  /**
+   * Creates an instance of a Leaflet Point
+   */
+  _newPoint: function(x, y) {
```
Comment (javisantana) [inline src/geo/leaflet/leaflet_cartodb_layergroup.js]: why this abstraction?

Comment (alonsogarciapablo) [inline src/geo/leaflet/leaflet_cartodb_layergroup.js]: I initially thought that this method was exactly the same for leaflet and gmaps, except for the instantiation of new points. I basically tried to make both methods look more alike.
